#!/bin/sh -e

readme () {
  echo ' '
  echo '########## Step1 add PATH ##########'
  echo '--- ~/.bashrc'
  echo '::'
  echo '# djb tool daemontools'
  echo 'export PATH=$PATH:$PREFIX/command'
  echo ' '
  echo '########## Step2 add service ##########'
  echo 'service dir is $PREFIX/service/ '
  echo ' '
  echo '########## Usage root user. ##########'
  echo '$ nohup sudo svscan $PREFIX/service/ &'
  echo ' '
  echo '# ps axu | grep supervise'
  echo '# ps axu | grep svscan'
  echo '# pstree'
  echo 'init─┬─'
  echo '     ::'
  echo '     ├─magiskd─┬─logcat'
  echo '     │         ├─sh───svscan───supervise───sh───sleep'
  echo '     │         ├─sh───bash─┬─less'
  echo '     │         │           └─pstree'
  echo ' '
  echo '########## Usage termux user. ##########'
  echo 'nohup svscan $PREFIX/service/ &'
  echo ' '
}

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

if test -d $PREFIX/service
then
  echo '$PREFIX/service exists. I assume that svscan is already running.'
  readme
  exit 0
fi

echo 'Creating $PREFIX/service...'
mkdir $PREFIX/service

if test -r /etc/inittab
then
  $PREFIX/command/setlock /etc/inittab package/run.inittab
else
  $PREFIX/command/setlock /etc/rc.local package/run.rclocal
fi

