#!/bin/sh -e

umask 022
test -d package || ( echo 'Wrong working directory.'; exit 1 )
test -d src || ( echo 'Wrong working directory.'; exit 1 )

here=`env - PATH=$PATH pwd`
parent=`dirname $here`

echo 'Creating symlink daemontools -> daemontools-0.76...'
rm -f daemontools
ln -s daemontools-0.76 daemontools
mv -f daemontools ..

echo 'Making command links in $PREFIX/command...'
mkdir -p $PREFIX/command
for i in `cat package/commands`
do
  rm -f $PREFIX/command/$i'{new}'
  ln -s $parent/daemontools/command/$i $PREFIX/command/$i'{new}'
  mv -f $PREFIX/command/$i'{new}' $PREFIX/command/$i
done
echo 'Making compatibility links in /usr/local/bin...'
mkdir -p $PREFIX/bin
for i in `cat package/commands`
do
  rm -f $PREFIX/bin/$i'{new}'
  ln -s $PREFIX/command/$i $PREFIX/bin/$i'{new}'
  mv -f $PREFIX/bin/$i'{new}' $PREFIX/bin/$i
done
